OUTPUT_PATH: ../results/pancake_experiment_stats.csv
NUM_TRIALS: 30
DOMAIN:
  NAME: pancake
  STATE_SIZE: [5, 6, 7, 8, 9]
SOLVER:
  - NAME: UCS()
    HEURISTIC: None
  - NAME: AStar()
    HEURISTIC: gap