EXPERIMENTS:
  - [pancake, [2,3,1,4], [1,2,3,4], UCS(), None]
  - [pancake, [1,5,2,4,3], [1,2,3,4,5], AStar(), gap]
  # - [pancake, [1, 9, 3, 4, 2, 5, 7, 8, 6, 10, 11, 13, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], UCS(), None]
  - [tile, [1, 0, 3, 4, 2, 5, 7, 8, 6], [1, 2, 3, 4, 5, 6, 7, 8, 0], UCS(), None]
  - [tile, [1, 0, 3, 4, 2, 5, 7, 8, 6], [1, 2, 3, 4, 5, 6, 7, 8, 0], AStar(), manhattan]
  # - [tile, [15, 2, 1, 12, 8, 5, 6, 11, 4, 9, 10, 7, 3, 14, 13, 0], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0], AStar(), manhattan]