OUTPUT_PATH: ../results/pancake_lrtastar_dqn.csv
NUM_TRIALS: 1
DOMAIN:
  NAME: pancake
  STATE_SIZE: [6]
SOLVER:
  # - NAME: UCS()
  #   HEURISTIC: None
  - NAME: AStar()
    HEURISTIC: gap
  # - NAME: RTAStar()
  #   HEURISTIC: manhattan
  - NAME: LRTAStar()
    HEURISTIC: gap
  # - NAME: LRTAStar()
  #   HEURISTIC: None